### ISSUE TITLE
Extend get_workspace endpoint

### ISSUE THREAD

**Issue by joschrew** [OCR-D/ocrd-webapi-implementation#22]
- This is about extending, not a bug report
- get_workspace currently requires an accept header to get either a json representation of the workspace or a zip. By default (no accept-header specified) this endpoint should return the json representation
- the json representation of the workspace contains the path to the workspace but ideally should additionally contain the workspace-id to clarify

**Comment by MehmedGIT** [comment]
The extensions are added as of v0.9.0.
